# Generated by Django 3.2.13 on 2022-08-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselor',
            name='img',
            field=models.ImageField(blank=True, default='/static/assets/img/student-icon.png', upload_to='img'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='img',
            field=models.ImageField(blank=True, default='/static/assets/img/student-icon.png', upload_to='img'),
        ),
        migrations.AlterField(
            model_name='student',
            name='img',
            field=models.ImageField(blank=True, default='/static/assets/img/student-icon.png', upload_to='img'),
        ),
    ]
