# Generated by Django 3.2.13 on 2022-08-23 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220819_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='student',
        ),
        migrations.AddField(
            model_name='todolist',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
