# Generated by Django 3.2.13 on 2022-09-07 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220823_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='student',
            field=models.ManyToManyField(blank=True, null=True, to='home.Student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='counselor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.counselor'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('freshman', 'FRESHMAN'), ('sophmore', 'SOPHMORE'), ('junior', 'JUNIOR'), ('senior', 'SENIOR'), ('grad', 'GRAD')], default='freshman', max_length=10),
        ),
    ]
