# Generated by Django 3.2.13 on 2022-09-10 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220907_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='student',
            field=models.ManyToManyField(blank=True, to='home.Student'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='assignee',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.user'),
        ),
    ]
